language: ruby
rvm:
- 2.0.0-p247
env:
- DB=sqlite
before_script:
- npm install
script:
- ./bin/test
deploy:
  provider: heroku
  api_key:
    secure: N5vquBOAkqY6JpyOaNz5kaxgXmdvg2kilaOr8oUguD7/ckWTbn/TOILdWzJ9oUKZgUVZWt/YdEH5DxAGVMctvMr4/iPk3y72sdDocKd+0gDyrTW8NDOKR/7Ol6PgqGsQEjN6mhMwM+trbQvMyL7a/DpLUQlz6B4sPL5HGG5tQWA=
  app: thebacklog
  on:
    repo: teamteam/backlog
notifications:
  hipchat:
    rooms:
      secure: XjPDs0zEVLN4NxOW8BnJO+XNrd8FiYzoy4UsOf6xanG4CrChv/epr/rQuZN+62Aw+vgqjV8GECEU0Do9TRu9+wZd0gyFsqE5h+bc6fCBe4Rmi415m0Y3lPqpxtfkWPJwjaTEZnuznu1HdiQ/BW1Dud0dsvDmN3OpF8H6W1YH2X8=
